target: all

server:
  http_listen_port: 3200

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks

compactor:
  ring:
    kvstore:
      store: inmemory

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
    - 127.0.0.1:7946