// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: department.sql

package db

import (
	"context"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (
  name
) VALUES (
  $1
)
RETURNING id, name, created_at
`
type CreateDepartmentParams struct {
    Name string `json:"name"`
}

func (q *Queries) CreateDepartment(ctx context.Context, name string) (Department, error) {
	row := q.db.QueryRowContext(ctx, createDepartment, name)
	var i Department
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, name, created_at FROM departments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDepartment(ctx context.Context, id int32) (Department, error) {
	row := q.db.QueryRowContext(ctx, getDepartment, id)
	var i Department
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, created_at FROM departments
ORDER BY id
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.QueryContext(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
