// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Department struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Professor struct {
	ID           int32         `json:"id"`
	FirstName    string        `json:"first_name"`
	LastName     string        `json:"last_name"`
	Email        string        `json:"email"`
	DepartmentID sql.NullInt32 `json:"department_id"`
	CreatedAt    time.Time     `json:"created_at"`
}

type Student struct {
	ID           int32         `json:"id"`
	FirstName    string        `json:"first_name"`
	LastName     string        `json:"last_name"`
	Email        string        `json:"email"`
	DepartmentID sql.NullInt32 `json:"department_id"`
	CreatedAt    time.Time     `json:"created_at"`
}
