// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: professor.sql

package db

import (
	"context"
	"database/sql"
)

const createProfessor = `-- name: CreateProfessor :one
INSERT INTO professors (
  first_name, last_name, email, department_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, first_name, last_name, email, department_id, created_at
`

type CreateProfessorParams struct {
	FirstName    string        `json:"first_name"`
	LastName     string        `json:"last_name"`
	Email        string        `json:"email"`
	DepartmentID sql.NullInt32 `json:"department_id"`
}

func (q *Queries) CreateProfessor(ctx context.Context, arg CreateProfessorParams) (Professor, error) {
	row := q.db.QueryRowContext(ctx, createProfessor,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.DepartmentID,
	)
	var i Professor
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DepartmentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProfessor = `-- name: DeleteProfessor :exec
DELETE FROM professors
WHERE id = $1
`

func (q *Queries) DeleteProfessor(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteProfessor, id)
	return err
}

const getProfessor = `-- name: GetProfessor :one
SELECT id, first_name, last_name, email, department_id, created_at FROM professors
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProfessor(ctx context.Context, id int32) (Professor, error) {
	row := q.db.QueryRowContext(ctx, getProfessor, id)
	var i Professor
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DepartmentID,
		&i.CreatedAt,
	)
	return i, err
}

const listProfessors = `-- name: ListProfessors :many
SELECT id, first_name, last_name, email, department_id, created_at FROM professors
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListProfessorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProfessors(ctx context.Context, arg ListProfessorsParams) ([]Professor, error) {
	rows, err := q.db.QueryContext(ctx, listProfessors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Professor
	for rows.Next() {
		var i Professor
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.DepartmentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
