// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateDepartment(ctx context.Context, name string) (Department, error)
	CreateProfessor(ctx context.Context, arg CreateProfessorParams) (Professor, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	DeleteProfessor(ctx context.Context, id int32) error
	GetDepartment(ctx context.Context, id int32) (Department, error)
	GetProfessor(ctx context.Context, id int32) (Professor, error)
	GetStudent(ctx context.Context, id int32) (Student, error)
	ListDepartments(ctx context.Context) ([]Department, error)
	ListProfessors(ctx context.Context, arg ListProfessorsParams) ([]Professor, error)
	ListStudents(ctx context.Context, arg ListStudentsParams) ([]Student, error)
}

var _ Querier = (*Queries)(nil)
